AAX_Exports.cpp File Reference
#include `AAX_Init.h`
#include `AAX.h`
#include `acfunknown.h`
#include `acfresult.h`
Macros
#define AAX_EXPORT extern `C` __declspec(dllexport) ACFRESULT __stdcall
Functions
AAX_EXPORT ACFRegisterPlugin (IACFUnknown *pUnkHostVoid, IACFPluginDefinition **ppPluginDefinitionVoid)
The main plug-in registration method.
AAX_EXPORT ACFRegisterComponent (IACFUnknown *pUnkHost, acfUInt32 index, IACFComponentDefinition **ppComponentDefinition)
Registers a specific component in the DLL.
AAX_EXPORT ACFGetClassFactory (IACFUnknown *pUnkHost, const acfCLSID &clsid, const acfIID &iid, void **ppOut)
Gets the factory for a given class ID.
AAX_EXPORT ACFCanUnloadNow (IACFUnknown *pUnkHost)
Determines whether or not the host may unload the DLL.
AAX_EXPORT ACFStartup (IACFUnknown *pUnkHost)
DLL initialization routine.
AAX_EXPORT ACFShutdown (IACFUnknown *pUnkHost)
DLL shutdown routine.
AAX_EXPORT ACFGetSDKVersion (acfUInt64 *oSDKVersion)
Returns the DLL's SDK version.
Macro Definition Documentation
AAX_EXPORT
#define AAX_EXPORT extern `C` __declspec(dllexport) ACFRESULT __stdcall
Function Documentation
ACFRegisterPlugin()
ACFAPI ACFRegisterPlugin (IACFUnknown * pUnkHost, IACFPluginDefinition ** ppPluginDefinition)
The main plug-in registration method.
References AAXRegisterPlugin().
ACFRegisterComponent()
ACFAPI ACFRegisterComponent (IACFUnknown * pUnkHost, acfUInt32 index, IACFComponentDefinition ** ppComponentDefinition)
Registers a specific component in the DLL.
References AAXRegisterComponent().
ACFGetClassFactory()
ACFAPI ACFGetClassFactory (IACFUnknown * pUnkHost, const acfCLSID & clsid, const acfIID & iid, void ** ppOut)
Gets the factory for a given class ID.
References AAXGetClassFactory().
ACFCanUnloadNow()
ACFAPI ACFCanUnloadNow (IACFUnknown * pUnkHost)
Determines whether or not the host may unload the DLL.
References AAXCanUnloadNow().
ACFStartup()
ACFAPI ACFStartup (IACFUnknown * pUnkHost)
DLL initialization routine.
References AAXStartup().
ACFShutdown()
ACFAPI ACFShutdown (IACFUnknown * pUnkHost)
DLL shutdown routine.
References AAXShutdown().
ACFGetSDKVersion()
ACFAPI ACFGetSDKVersion (acfUInt64 * oSDKVersion)
Returns the DLL's SDK version.
References AAXGetSDKVersion().